# Generated by Django 2.2.3 on 2019-07-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='university.Department'),
        ),
    ]
